name: run2gether
favicon: null
layout_spectrum: 0.36224442534148693
typography_spectrum: 0.38879139465279877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.25394118134863675
  lightness: 0.29495475301519036
  saturation: 0.7358708344399929
  rhythmicContrast: 0.641347395023331
purpose: []
