name: run2gether
favicon: null
layout_spectrum: 0.75024
typography_spectrum: 0.15671
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffcb05'
    - '#231f20'
    - '#d42b2e'
    - '#3cac4a'
  brandStrength: 0.25394118134863675
  lightness: 0.29495475301519036
  saturation: 0.7358708344399929
  rhythmicContrast: 0.641347395023331
purpose: []
